### ISSUE TITLE
Misleading stat output for all time instead of time range in v0.8.0

### ISSUE THREAD

**Issue by p5i** [VictoriaMetrics/victorialogs-datasource#119]
When using the 'Stat', 'Gauge' or other similar visualizations in Grafana, the stats query on the dashboard
`* | stats count()`
transforms to this query to VL
`POST /select/logsql/stats_query?query=%2A+%7C+stats+count%28%29&time=1732387652` 
There is only one time constraint. Because of this, instead of getting stats for the specified on the dashboard time range, we receive stats for all the time before the upper bound.
![photo_1](https://github.com/user-attachments/assets/f8579072-0a54-43b5-be63-6a61f933e601)

This looks misleading because for Grafana it is common to receive data only for the time period specified on the dashboard.

This can be worked around by specifying the time filter with Grafana's global variables '$__from' and '$__to'.
`_time: [$__from, $__to] | stats count()` 
![photo_2](https://github.com/user-attachments/assets/b2fed7a1-d5bc-4712-97e9-54be3726387a)

But it looks hacky for such a common query.

I think it would be better to transform the stats query in Grafana to the VL query with time range
```
$ curl -s http://localhost:9428/select/logsql/stats_query -d 'query= * | stats count()' -d 'start=now-1d' -d 'end=now' | jq
{
  "status": "success",
  "data": {
    "resultType": "vector",
    "result": [
      {
        "metric": {
          "__name__": "count(*)"
        },
        "value": [
          1732388516.0014431,
          "2167582"
        ]
      }
    ]
  }
}
```
This form of stats_query is not documented here [https://docs.victoriametrics.com/victorialogs/querying/#querying-log-stats](https://docs.victoriametrics.com/victorialogs/querying/#querying-log-stats) , but I think it should be. And it works correctly as far as I can tell.

**Comment by p5i** [comment]
Hi @dmitryk-dk. Thanks for the answer. I think  #111 is exactly what I asked here and https://github.com/VictoriaMetrics/victorialogs-datasource/issues/112 can help to optimize the queries with the time filter.

**Comment by hagen1778** [comment]
@dmitryk-dk @Loori-R I think what @p5i says about instant panels has a lot of sense.

It is unlikely someone will need to have a panel on dashboard that does `stats` over the all retentionPeriod, as it is very expensive calculation. I think it would be reasonable to do the following changes to stats panels:
* automatically apply time filter to all instant panels. I.e. `* | stats count()` should be automatically transformed by backend to `* _time:$__range | stats count()`
* Don't transform the query if it already has `_time:` specified, as user might wanted to apply some custom filter like `7d`, etc.
* When switched to `range` type of query (for getting timeseries-like visual on panel background), plugin should apply similar time filter transforamtion as above. It should use the last value from response as main number displayed on stats panel. And the rest of response for backround visualization.

**Comment by hagen1778** [comment]
@dmitryk-dk @Loori-R about the 3rd point "When switched to range type of query (for getting timeseries-like visual on panel background)" looks like I was wrong
1. This is Instant
<img width="1285" alt="image" src="https://github.com/user-attachments/assets/066b1683-086c-4a2d-8d3b-1c770fbab396">
2. This is Range
<img width="1298" alt="image" src="https://github.com/user-attachments/assets/8f5853aa-0faf-4d0e-ae9e-62f00f5b18bc">

As you see, values changing a lot because:
1. Instant query is cumulative over all interval
2. Range query has `step`, so it shows aggregations per step and displays as big number the last value from the returned list of datapoints

In order to make stats panels with Range type of query correct we can do two things:
1. Sum all returned values in Grafana, aggregate the result in other words
2. Send two queries: one range and one instant to the backed. Range for background, instant for cumulative results. This would have performance bottleneck

Loki datasource does the 2nd. I suspect, finishing aggregation on frontend isn't 100% correct. But we should verify why it is so, maybe some details in loki implementation are related.

**Comment by krzysion** [comment]
For "range" you can achieve the same result by selecting from Value options - Calculation: Total, it works similarly in Loki with the count_over_time function.
![Zrzut ekranu 2024-12-10 221921](https://github.com/user-attachments/assets/9f324049-b457-4b04-a56f-0e00808b3bcf)
![Zrzut ekranu 2024-12-10 221938](https://github.com/user-attachments/assets/000d53d5-1b58-47d2-b37f-59dea5bcef55)

**Comment by hagen1778** [comment]
Thanks! Then, I think, this ticket can be closed.

**Comment by dmitryk-dk** [comment]
Close the issue as solved. Feel free to reopen it if you find any problems.
